# version: "3.3"
# services:
#   web:
#     image: rajatrokde9/python-app:v2
#     build:
#       context: .
#     ports:
#       - 7000:7000
services:
  web:
    image: rajatrokde9/python-app:v2
    build: .
    ports:
      - "7000:7000"  
    environment:
      - FLASK_RUN_HOST=0.0.0.0
