apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: rajatrokde/python-app:v2
        ports:
        - containerPort: 7000
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: default
spec:
  type: ClusterIP   # <-- changed from NodePort to ClusterIP
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 7000