image: python:3.9-slim

stages:
  - build
  - test
  - docker-build
  - deploy

# variables:
#   APP_PORT: 5000

build-job:
  stage: build
  tags:
    - local
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - python --version
    - pip install --upgrade pip --break-system-packages
    - pip install -r requirements.txt
    - pip install gunicorn

test-job:
  stage: test
  tags:
    - local
  script:
    - echo "Starting Gunicorn..."
    - gunicorn --bind 0.0.0.0:$APP_PORT todo_app:app &   # make sure this matches your app entry point
    - echo "Waiting for app to start..."
    - for i in {1..10}; do curl -s http://localhost:$APP_PORT && break || sleep 5; done

docker-build:
  stage: docker-build
  tags:
    - local
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:gitlab .
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:gitlab

deploy:
  stage: deploy
  tags:
    - local
  script:
    - docker pull $DOCKER_USERNAME/$DOCKER_IMAGE:gitlab
    - docker stop $DOCKER_IMAGE || true
    - docker rm $DOCKER_IMAGE || true
    - docker run -d -p $APP_PORT:$APP_PORT --name $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:gitlab
