name: Docker CI/CD

on:
  push:
    branches:
      - main
     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:v2
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy container
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:v2
          docker stop mycontainer || true
          docker rm mycontainer || true
          docker run -d -p 80:80 --name website $IMAGE_NAME
