name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Changed from self-hosted to ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set IMAGE_NAME environment variable
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:github" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest  # Changed from self-hosted to ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:github

      - name: Run Docker container
        run: |
          docker rm -f todo_app_container || true
          docker run -d -p 7000:7000 --name todo_app_container ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:github
