name: Run Python App

on:
  push:
    branches:
      - main  # or your desired branch
  pull_request:
    branches:
      - main  # or your desired branch

jobs:
  run_python_app:
    runs-on: [self-hosted, linux]  # Use 'windows' or 'linux' depending on your runner environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt for dependencies

    - name: Run Python Application
      run: |
        python app.py  # Replace 'app.py' with your entry point
