name: Deploy and Runs Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_and_run:
    runs-on: [self-hosted, linux]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn  # Add only if needed and not in requirements.txt

    - name: Run Python Application with Gunicorn
  run: 
    gunicorn todo_app:app --bind 0.0.0.0:5000 &
    sleep 10  # optional: wait and then run health checks or tests
  #- name: Health Check
      #run: curl --fail http://localhost:5000 || exit 1

   
